overrides:
  ceph:
    log-ignorelist:
  check-counter:
    counters:
      mds:
        - mds.root_rsnaps
        - mds_server.req_mksnap_latency.avgcount
        - mds_server.req_rmsnap_latency.avgcount
tasks:
- exec:
    mon.a:
      - ceph mgr module enable snap_schedule
      - ceph config set mgr mgr/snap_schedule/allow_m_granularity true
      - ceph config set mgr mgr/snap_schedule/dump_on_update true
      - ceph fs snap-schedule add --fs=cephfs --path=/ --snap_schedule=1M
      - ceph fs snap-schedule retention add --fs=cephfs --path=/ --retention-spec-or-period=12M3h
      - ceph fs snap-schedule status --fs=cephfs --path=/
      - ceph fs snap-schedule list --fs=cephfs --path=/ --recursive=true
- full_sequential_finally:
  - exec:
      mon.a:
        - ceph fs snap-schedule status --fs=cephfs --path=/
        - ceph fs snap-schedule list --fs=cephfs --path=/ --recursive=true
